### ISSUE TITLE
Black text on black background

### ISSUE THREAD

**Issue by mkyral** [jtyr/plasma-tempreader#3]
Widget works fine with default plasma theme, but not well with dark plasma theme.

![obrazek](https://user-images.githubusercontent.com/155542/36325843-5de6dfbc-1359-11e8-9620-d13ebf0f5fff.png)

**Comment by jtyr** [comment]
This should be fixed now via https://github.com/jtyr/plasma-tempreader/commit/46172f680afa95e9ba3346eef5c795d334ddb712.
